### ISSUE TITLE
Obfuscation mappings exist for classes, but not fields.

### ISSUE THREAD

**Issue by char** [ImpactDevelopment/ClientAPI#1]
If you want to be able to run the client from a notch obfuscated state, you will need to save a mapping for fields as well.

Raw MCP names are used in this example:
https://github.com/ZeroMemes/ClientAPI/tree/master/src/main/java/me/zero/client/load/transformer/defaults/TRenderManager.java#L32

You should probably store fields here:
https://github.com/ZeroMemes/ClientAPI/blob/master/src/main/java/me/zero/client/load/transformer/reference/obfuscation/MCMappings.java

**Comment by ZeroMemes** [comment]
Thank you for reporting the issue, it has been fixed by commit 477f802ed2d1099795c8921afb004c6b564be170.
