### ISSUE TITLE
Move feather to maven

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ClientAPI#14]
In order to remove [Feather] from this repo, we should distribute it on the [Impact maven][maven] and simply list it in our `build.gradle` as a dependency.

[feather]: /KNOXDEV/feather
[maven]: /ImpactDevelopment/maven

**Comment by LeafHacker** [comment]
I've made a fork of the Feather repo on the @ImpactDevelopment group, which will allow us to set it up with travis and packagecloud as per #18

**Comment by ZeroMemes** [comment]
Fixed by ImpactDevelopment/maven@8670c53 in ee9ef21
