### ISSUE TITLE
Unable to locate the Client.json when running without CDK

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ClientAPI#15]
It should be possible to test ClientAPI by running the example Client _without_ having to setup the CDK with a dev build.

Attempting to run the client using the `client-api_test` module results in this uncaught exception: `ClientInitException: Unable to locate the Client.json`.

Please see the full [crash log](https://github.com/ZeroMemes/ClientAPI/files/1213730/capi-crash.txt) and [run config](https://user-images.githubusercontent.com/23565638/29155730-c7338128-7d95-11e7-91a5-be3cf594ea10.png).

**Comment by LeafHacker** [comment]
Would probably be fixed by creating an `example` source set which includes the `main` source set as a dependency

**Comment by ZeroMemes** [comment]
Fixed by 5a1ea30. The module needs to be set to example to run.
