### ISSUE TITLE
Move @Accessor mixins from interfaces to main mixin classes

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ClientAPI#20]
In #9 We started implementing `@Accessor` and `@Invoker` mixins. Because it (appeared to) use less boilerplate, we added them to the wrapper interfaces (e.g. `ICPacketPlayer`) which works well, until you need non-accessor members on the interface, e.g. to add new methods.

Instead of using accessor interfaces where we can and wrapper interfaces where we must, we should instead be consistent and move _all_ mixin stuff (including accessors) into the main mixin class, and simply expose them via the interface.

**Comment by ZeroMemes** [comment]
I haven't been keeping up with issues, but it appears that all accessors have been placed inside of the main mixin classes, and are exposed by the interfaces, so this may be closed.
