### ISSUE TITLE
EntityDeathEvent not fired for EntityPlayerSP (2.1)

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ClientAPI#25]
At least in single player, `EntityDeathEvent` isn't fired when `EntityPlayerSP` dies.

This may be because `EntityPlayerSP` is not ticked when it is dead, but since I've not looked into this that is pure speculation.

Tested against 2.1

**Comment by ZeroMemes** [comment]
Should be fixed in 279381961ff8f66d2c951dabf478d5e315a1ada0. I'll check before closing

**Comment by LeafHacker** [comment]
Assume this was successfully fixed
