### ISSUE TITLE
DefaultWidgetAlignment is inverted

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ClientAPI#26]
`LEFT` is `-1` and `RIGHT` is `+1`, which is inverted. This is demonstrated in Impact's HUD alignment, where right-aligned widgets like mod list and coords are initiated with `LEFT` alignment

**Comment by ZeroMemes** [comment]
``LEFT`` means adjust the widget to be on the left side of the center on the y-axis, so elements on the right side of the screen would need to be aligned to the left side.
