### ISSUE TITLE
Dead URL in README

### ISSUE THREAD

**Issue by winnpixie** [ImpactDevelopment/ClientAPI#31]
https://github.com/ImpactDevelopment/ClientAPI/tree/master/src/main/java/clientapi/load (near the bottom of the README for the Tweaker class information) doesn't exist anymore and just 404's (probably due to multiple branches existing now), valve pls fix

**Comment by ghost** [comment]
see https://github.com/ImpactDevelopment/ClientAPI/pull/32

**Comment by ZeroMemes** [comment]
I fixed this a bit ago, not gonna search for commit lol.

**Comment by SpicyBigGithub** [comment]
Fix it 😡😡
