### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by GramDev1** [ImpactDevelopment/ClientAPI#7]
How would I go about settings this up? Readme says instructions to be posted and yet there are none in any of the associated repos.
thanks

**Comment by ZeroMemes** [comment]
Are you looking at making a client or contributing to the API?

**Comment by GramDev1** [comment]
Well, both

**Comment by ZeroMemes** [comment]
The [CDK](https://github.com/ZeroMemes/ClientAPI-CDK) is used to develop clients. This is set up the same way one would go about setting up forge.

To setup an environment to contribute to the API, please contact me on Discord. (Complex Process, very messy) Brady#4207
